src/beans/Comment.java
/**
 *
 */
package beans;

import java.io.Serializable;
import java.util.Date;

/**
 * @author ogawa.ayaka
 *
 */
public class Comment implements Serializable{
	private static final long serialVersionUID = 1L;

	private int id;
	public int getId(){
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	private int userId;
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}

	private int message_Id;
	public int getMessageId() {
		return message_Id;
	}
	public void setMessageId(int message_Id) {
		this.message_Id = message_Id;
	}

	private String comment;
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}

	private Date created_date;
	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}

	private Date updated_Date;
	public Date getUpdated_Date() {
		return updated_Date;
	}
	public void setUpdated_Date(Date updatedDate) {
		this.updated_Date = updatedDate;
	}


}

src/beans/Message.java
/**
 *
 */
package beans;

import java.io.Serializable;
import java.util.Date;

/**
 * @author ogawa.ayaka
 *
 */
public class Message implements Serializable{
	private static final long serialVersionUID = 1L;


	private int id;
	public int getId(){
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}


	private int userId;
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}

	private String title;
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	private String category;
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;

		}

	private String message;
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}

	private Date created_Date;
	public Date getCreated_Date() {
		return created_Date;
	}
	public void setCreated_Date(Date createdDate) {
		this.created_Date = createdDate;
	}


	private Date updated_Date;
	public Date getUpdated_Date() {
		return updated_Date;
	}
	public void setUpdated_Date(Date updatedDate) {
		this.updated_Date = updatedDate;
	}



}

src/controller/LoginServlet.java
/**
 *
 */
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;

/**
 * @author ogawa.ayaka
 *
 */
@WebServlet(urlPatterns = {"/login"})
public class LoginServlet extends HttpServlet{
	private static final long serialVersionUID = 1L;


	@Override
	protected void doGet(HttpServletRequest request,HttpServletResponse response)throws IOException, ServletException{

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException{

		String account = request.getParameter("account");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		User user = loginService.login(account, password);


		HttpSession session = request.getSession();
		if(user != null) {

			session.setAttribute("loginUser", user);
			response.sendRedirect("./");
		}else {

			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}
	}

}

src/controller/SignUpServlet.java
/**
 *
 */
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Branch;
import beans.Department;
import beans.User;
import service.BranchService;
import service.DepartmentService;
import service.UserService;

/**
 * @author ogawa.ayaka
 *
 */
@WebServlet(urlPatterns = {"/signup"})
public class SignUpServlet extends HttpServlet{
	private static final long serialVersionUID = 1L;


	@Override
	protected void doGet(HttpServletRequest request,HttpServletResponse response) throws IOException, ServletException{

		List<Branch> branches = new BranchService().getBranchlist();
		request.setAttribute("branches", branches);

		List<Department> departments = new DepartmentService().getDepartmentlist();
		request.setAttribute("departments", departments);


		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}


	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException{


		List<String> messages = new ArrayList<String>();


		HttpSession session = request.getSession();

		User user = new User();
		user.setName(request.getParameter("name"));
		user.setAccount(request.getParameter("account"));
		user.setPassword(request.getParameter("password"));
		user.setBranch_id(Integer.parseInt(request.getParameter("branch_id")));
		user.setDepartment_id(Integer.parseInt(request.getParameter("department_id")));

		String account =user.getAccount();
		User accountCnfilm = new UserService().accountConfilm(account);


		if(isValid(request, messages, user) == true) {



			new UserService().register(user);

			response.sendRedirect("user_managements");

		}else {
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("signup");
		}

	}


	private boolean isValid(HttpServletRequest request, List<String> messages, User user) {
		String account = request.getParameter("account");
		String password = request.getParameter("password");

		//int branch_id = Integer.parseInt(request.getParameter("branch_id"));
		//int department_id = Integer.parseInt(request.getParameter("department_id"));

		int branch_id = user.getBranch_id();
		int department_id = user.getDepartment_id();

		if (StringUtils.isEmpty(account) == true) {
			messages.add("アカウント名を入力してください");
		}
		if (StringUtils.isEmpty(password) == true) {
			 messages.add("パスワードを入力してください");
		}

		if((branch_id == 1) &&( department_id >= 3)){
			messages.add("支店名と部署・役職名が不一致です");
		}

		if((branch_id != 1)&& (department_id <= 2)) {
			messages.add("支店名と部署・役職名が不一致です");
		}



		if (messages.size() == 0) {
			return true;
		}else {
			return false;
		}
	}
}

src/controller/TopServlet.java
/**
 *
 */
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import beans.UserComment;
import beans.UserMessage;
import service.CommentService;
import service.MessageService;



/**
 * @author ogawa.ayaka
 *
 */

@WebServlet(urlPatterns = {"/index.jsp"})
public class TopServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,HttpServletResponse response) throws IOException, ServletException {



		String start = request.getParameter("start");
		String end = request.getParameter("end");
		String search = request.getParameter("search");

		//System.out.println(start);
		//System.out.println(end);
		//System.out.println(search);

		List<UserMessage> messages = new MessageService().getMessage(start, end,search);

		request.setAttribute("messages", messages);


		List<UserComment> comments = new CommentService().getComment();

		request.setAttribute("comments", comments);

		HttpSession session = request.getSession();
		User loginUser =(User) session.getAttribute("loginUser");

		request.setAttribute("loginUser", loginUser);







		request.getRequestDispatcher("/top.jsp").forward(request, response);

	}

}

src/controller/UserManagementsServlet.java
/**
 *
 */
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.Branch;
import beans.Department;
import beans.User;
import service.BranchService;
import service.DepartmentService;
import service.UserService;

/**
 * @author ogawa.ayaka
 *
 */
@WebServlet(urlPatterns = {"/user_managements"})
public class UserManagementsServlet extends HttpServlet{

	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request,HttpServletResponse response) throws IOException, ServletException{

		List<User> users =  new UserService().getUserslist();

		request.setAttribute("users", users);

		List<Branch> branches = new BranchService().getBranchlist();

		//System.out.println(branches.get(0).getBranch_name());

		request.setAttribute("branches", branches);

		List<Department> departments = new DepartmentService().getDepartmentlist();
		request.setAttribute("departments", departments);


		request.getRequestDispatcher("/user_management.jsp").forward(request, response);

	}

	protected void doPost(HttpServletRequest request,HttpServletResponse response)throws IOException, ServletException{


		User switchUser = new User();
		switchUser.setId(Integer.parseInt(request.getParameter("id")));
		switchUser.setIs_stopped(Integer.parseInt(request.getParameter("is_stopped")));

		//System.out.println(switchUser.getIs_stopped());

		new UserService().stopped(switchUser);

		response.sendRedirect("user_managements");



	}




}

src/controller/UserSettingServlet.java
/**
 *
 */
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Branch;
import beans.Department;
import beans.User;
import exception.NoRowsUpdatedRuntimeException;
import service.BranchService;
import service.DepartmentService;
import service.UserService;

/**
 * @author ogawa.ayaka
 *
 */

@WebServlet(urlPatterns = {"/user_settings"})
public class UserSettingServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	List<Branch> branches = new BranchService().getBranchlist();
	List<Department> departments = new DepartmentService().getDepartmentlist();

	@Override

	protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException{


		int id = Integer.parseInt(request.getParameter("id"));
		User editUser = new UserService().getUser(id);

		request.setAttribute("editUser", editUser);


		request.setAttribute("branches", branches);
		request.setAttribute("departments", departments);

		request.getRequestDispatcher("user_settings.jsp").forward(request, response);

	}

	@Override
	protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException{

		List<String> messages = new ArrayList<String>();


		HttpSession session = request.getSession();


		User editUser = getEditUser(request);

		//String account = request.getParameter("account");
	//	User accountCnfilm = new UserService().getUser(account);

		if(isValid(request, messages, editUser)) {

			try {

				new UserService().update(editUser);

			}catch(NoRowsUpdatedRuntimeException e) {
				messages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
				session.setAttribute("errorMessages", messages);
				request.setAttribute("editUser", editUser);
				request.getRequestDispatcher("user_settings.jsp").forward(request, response);
                return;

			}
			 session.setAttribute("id", editUser);
			 response.sendRedirect("user_managements");

		}else {
			session.setAttribute("errorMessages", messages);
			request.setAttribute("editUser", editUser);
			request.setAttribute("branches", branches);
			request.setAttribute("departments", departments);
			request.getRequestDispatcher("user_settings.jsp").forward(request, response);


		}

	}

	private User getEditUser(HttpServletRequest request)throws IOException, ServletException{

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setName(request.getParameter("name"));
		editUser.setAccount(request.getParameter("account"));
		editUser.setPassword(request.getParameter("password"));
		editUser.setBranch_id(Integer.parseInt(request.getParameter("branch_id")));
		editUser.setDepartment_id(Integer.parseInt(request.getParameter("department_id")));
		return editUser;
	}

	private boolean isValid(HttpServletRequest request, List<String> messages, User editUser){

		String account = request.getParameter("account");
        String password = request.getParameter("password");
        String passwordConfirm =request.getParameter("passwordConfirm");
        int branch_id = editUser.getBranch_id();
        int department_id = editUser.getDepartment_id();



        if (StringUtils.isEmpty(account) == true) {
            messages.add("アカウント名を入力してください");
        }
        if (StringUtils.isEmpty(password) == true) {
            messages.add("パスワードを入力してください");
        }
        if(!(password.equals( passwordConfirm)) ) {
        	messages.add("パスワードと確認用パスワードが一致しません");

        }


        if(!password.matches("^[a-zA-Z0-9 -/:-@\\[-\\`\\{-\\~]{6,20}$")) {


        	messages.add("パスワードは半角英数字記号かつ6～20文字で入力してください");
        }

         if(!(account.matches("^[a-zA-Z0-9 -/:-@\\[-\\`\\{-\\~]{6,20}$")) ) {
        	 messages.add("アカウントは半角英数字記号かつ6～20文字で入力してください");

         }

        if(branch_id == 1 && department_id >= 3) {
        	messages.add("支店名と部署・役職名が不一致です");
        }

        if(branch_id != 1 && department_id <= 2) {
        	messages.add("支店名と部署・役職名が不一致です");
        }

        if (messages.size() == 0) {
            return true;
        }else {
        	return false;
        }


	}



}

WebContent/User_settings.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>編集</title>
	</head>
	<body>

	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">

			<div class = "errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>

				</ul>
			</div>
			<c:remove var = "errorMessages" scope = "session"/>

		</c:if>

		<form action = "user_settings" method = "post">	<br/>
			<input name="id" value="${editUser.id}" id="id" type="hidden"/>
			<label for="name">名前</label>
			<input name="name" value="${editUser.name}" id="name"/>（名前はあなたの公開プロフィールに表示されます）<br />

			<label for="account">アカウント名</label>
			<input name="account" value="${editUser.account}" /><br />

			<label for="password">パスワード</label>
			<input name="password" type="password" id="password" required><br />

			<label for="passwordConfirm">パスワード（確認）:</label>
			<input type="password" name="passwordConfirm" id="passwordConfirm" required><br>


			<div class = "branches">支店名
			<select name = "branch_id">
				<c:forEach items = "${branches}" var= "branch">
					<option value = "${ branch.id}"> ${branch.branch_name} </option>
				</c:forEach>
			</select>
			</div>

			<div class = "departments">部署・役職名
			<select name = "department_id">
				<c:forEach items = "${departments}" var = "department">
					<option value = "${department.id}">${department.department_name}</option>
				</c:forEach>
			</select>
			</div>
			<input type="submit" value="登録" /> <br />
		</form>


		 <a href="user_managements">戻る</a>

	<div class = "copyright">Copyright(c)ogawa ayaka</div>
	</div>
	</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
		<title>ログイン</title>
	</head>
	<body>
		<div class = "main-contents">

		<c:if test = "${not empty errorMessages }">
			<div class = "errorMessages">
			<ul>
				<c:forEach items = "${errorMessages }" var = "message">
					<li><c:out value = "${message }"/>
				</c:forEach>
			</ul>
		    </div>
		<c:remove var = "errorMessages" scope = "session"/>
		</c:if>

		<form action = "login" method = "post"><br/>
			<label for = "account">アカウント名</label>
			<input name = "account" id = "account"/><br/>

			<label for = "password">パスワード</label>
			<input name="password" type="password" id="password" /><br/>
			<input type = "submit" value = "ログイン"/><br/>

		</form>
		<div class="copyright"> Copyright(c)ogawa ayaka</div>
	     </div>

	</body>
</html>

WebContent/messages.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
		<title>	新規投稿画面</title>
	</head>
	<body>

	＜＜新規投稿画面＞＞
	<br/>
		<div class = "mamin-contents">

			<form action="messages" method="post">

			<label for = "title" >件名</label>
			<input name = "title" id = "title"/><br/>

			<label for = "category">カテゴリー</label>
			<input name = "category" id = "category"><br/>



			新規投稿<br/>
			<textarea name="message" cols="100" rows="5" class="tweet-box" id = "message"></textarea>

			<br/>
			<input type="submit" value="投稿" >（1000文字まで）

			<a href = "./">戻る</a>

			</form>
			<div class = "copyright">Copyright(c)ogawa ayaka</div>
		</div>

</body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
	<title>ユーザー新規登録</title>
	</head>
	<body>
		<div class = "mamin-contents">
		<c:if test = "${not empty errorMessages }">
			<div class = "errorMessages">
				<ul>
					<c:forEach items = "${errorMessages}" var = "message">
					<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var = "errorMessages" scope = "session"/>
		</c:if>
		<form action = "signup" method = "post">
			<br/><label for = "name">名前</label>
			<input name = "name" id = "name"/>

			<br/><label for ="account">アカウント名</label>
			<input name="account"id="account" />

			<br/> <label for="password">パスワード</label>
			<input name="password" type="password" id="password" />

			<div class = "branches">支店名

				<select name = "branch_id">
					<c:forEach items ="${branches}" var = "branch" >
						<option value = "${branch.id}"> ${branch.branch_name}</option>
					</c:forEach>
				</select>
			</div>

			<div class = "departments">部署・役職名
				<select name = "department_id">
					<c:forEach items = "${departments}" var = "department">

						<option value = "${department.id}"> ${department.department_name}</option>

					</c:forEach>
				</select>
			</div>
			<input type = "submit" value = "登録"/>

			<br/>
			<a href = "user_managements">戻る</a>
		</form>
		<div class = "copyright">Copyright(c)ogawa ayaka</div>
	</div>

	</body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
  		<meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
		<title>ホーム画面</title>
	</head>
	<body>

	＜＜ホーム画面＞＞

	<div class = "main-contents">
			<br/><div class = "header">
			<!-- <a href = "signup">ユーザー新規登録</a>-->
			<a href = "user_managements">ユーザー管理</a>
			<a href = "messages">新規投稿</a>
			<a href="logout">ログアウト</a>
			</div>
		</div>
		<br/><c:set value = "${loginUser}" var = "loginUser"/>
		ログインユーザー名：<c:out value = "${loginUser.name}"/><br/>



		<br/>
			<div class = "date">
		<form action = "index.jsp" method = "get">
			日付検索：<input type = "date" name = "start" value = "${start}" >
			～ <input type = "date" name = "end" value ="${end}">
				<!--  <input type="submit" value="検索">-->
			<!-- /form-->
			</div>

			<br/>
			<div class = "search">
			<!--  form action = "index.jsp" method = "get"-->
			カテゴリー検索:<input type = "text" name = "search" value = "${search }">
			<input type = "submit" value = "検索">
		</form>
		</div>

		<div class = "messages">
			<c:forEach items="${messages}" var="message">
				<div class = "message">
					<br/>名前<div class="name"><c:out value="${message.name}" /></div>
					<br/>件名<div class = "title"><c:out value="${message.title}" /></div>
					<br/>カテゴリー<div class = "category"><c:out value="${message.category}" /></div>
					<br/>投稿文<div class = "message"><c:out value = "${message.message}"/></div>
					<br/>投稿日時<div class="date"><fmt:formatDate value="${message.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>


					<c:set value = "${loginUser}" var = "loginUser"/>
					<c:if test = "${loginUser.id == message.userId}">
						<div class = "deletemessages">
							<form action = "deletemessages " method = "post">
								<input type = "hidden" name = "message_id" value = "${message.id}">
								<input type = "submit" value ="投稿削除">(上記の内容を削除します)
							</form>
						</div>
					</c:if>
					<br>
				</div>


				<div class = "new-commenst">
				<form action = "comments" method = "post">
					コメント<br/>
					<textarea name="comment" cols="100" rows="5" class="tweet-box" id = "comment"></textarea>
					<input type = "hidden" name = "message_id" id = "message_id " value = "${message.id}">
					<input type="submit" value="コメント" >（500文字まで）
				</form>
				</div>

				<br/><div class = "comments">
					<c:forEach items = "${comments}" var= "comment">
						<c:if test = "${message.id == comment.messageId}">
							<div class = "name">名前：<c:out value = "${comment.name}"/>
							</div>
							<div class="comment">コメント内容：<c:out value="${comment.comment}" /></div>
							<div class="date">投稿日時：<fmt:formatDate value="${comment.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>

								<div class = "deletecomments">
									<form action = "deletecomments" method = "post">
									<c:set value = "${loginUser}" var = "loginUser"/>
									<c:if test = "${loginUser.id == comment.userId}">
										<input type = "hidden" name = "comment_id" value = "${comment.id}">
										<input type = "submit" value = "コメント削除">（上記内容を削除します）
									</c:if>
									</form>
								</div>
						</c:if>
				</c:forEach>
				</div>
			</c:forEach>
		</div>


		<br/><div class = "copyright">Copyright(c)ogawa ayaka</div>





	</body>
</html>

WebContent/user_management.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
		<title>ユーザー管理画面</title>
	</head>
	<body>

	＜＜ユーザー管理画面＞＞<br/>

	<div class = "main-contents">

		<br/><a href = "signup">ユーザー新規登録</a><br/>


		<br/>＜＜ユーザー一覧＞＞

			<c:forEach items = "${users}" var = "user">

			<div class = "user">

				<br/>アカウント<div class = "account"><c:out value = "${user.account}"/></div>
				<br/>名前<div class = "name"><c:out value = "${user.name}"/></div>



				<div class = "branches">
				<c:forEach items = "${branches}" var= "branch">

					<c:if test = "${user.branch_id == branch.id}">
						<br/>支店名
						<div class = "name"><c:out value = "${branch.branch_name}"/></div>

					</c:if>

				</c:forEach>
				</div>

				<c:forEach items = "${departments}" var= "department">
				<c:if test = "${user.department_id == department.id}">
					<br/>部署
					<div class = "name"><c:out value = "${department.department_name}"/></div>
				</c:if>
				</c:forEach>


				<br/>ユーザー情報<div class = "is_stopped">
				<form action = "user_managements" method = "post">
					<c:if test = "${user.is_stopped == 1}">
						<input type = "submit" name = "button" value = "復活" onclick="return confirm('ユーザーを復活します。よろしいですか？')">
						<input name = "is_stopped" value = "0" type = "hidden">

					</c:if>

					<c:if test = "${user.is_stopped == 0 }">

						<input type = "submit" name = "button" value = "停止" onclick="return confirm('ユーザーを停止します。よろしいですか？')">
						<input name ="is_stopped" value = "1" type = "hidden">

					</c:if>

					<input name="id" value="${user.id}" id="id" type="hidden"/>



					 <c:out value = "${user.is_stopped}"/>

				</form>
					 </div>





				<br/>
				<a href = "user_settings?id=${user.id}">ユーザー編集</a>

			</div>

			</c:forEach>






			<a href = "./">戻る</a>

	</div>

	<div class = "copyright">Copyright(c)ogawa ayaka</div>



	</body>
</html>